---
- name: Configure OPS445 Linux VM for Labs
  hosts: vmlab
  user: student
  become: yes
  tasks:
    - name: Update Apache (httpd) package
      yum:
        name: httpd
        state: latest

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Remove tree package
      yum:
        name: tree
        state: absent

    - name: Set the hostname
      hostname:
        name: "pspatel53"

    - name: Create user with sudo access
      user:
        name: "pspatel53"
        state: present
        shell: /bin/bash
        groups: wheel

    - name: Ensure the new user can SSH without a password
      authorized_key:
        user: "pspatel53"
        state: present
        key: "{{ lookup('file', '/home/pspatel53/.ssh/id_rsa.pub') }}"

    - name: Create lab directories
      file:
        path: "/home/pspatel53/ops445/lab{{ item }}"
        state: directory
        mode: '0755'
        owner: "pspatel53"
        group: "pspatel53"
      loop: "{{ range(1, 9) | list }}"

    - name: Ensure Apache service is started
      service:
        name: httpd
        state: started
        enabled: yes
